In [8]:
import numpy as np
import pandas as pd

X=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(X)

print(X.shape)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
import random
X=np.insert(X,0,1,axis=1)
print(X)


[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]


In [13]:
# numpy.ones(shape, dtype=None, order='C')

X=np.ones((3,3),dtype=int,order='C')
print(X)

X=np.zeros((3,3))
print(X)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np

# Create a 1-dimensional array of 5 ones (float by default)
arr1 = np.ones(5)
print("1D array (float):")
print(arr1)
print(arr1.dtype) # Output: float64

print("-" * 20)

# Create a 2x3 array of ones (float by default)
arr2 = np.ones((2, 3))
print("2D array (float):")
print(arr2)

print("-" * 20)

# Create a 3x3 array of ones with integer data type
arr3 = np.ones((3, 3), dtype=np.int32)
print("3x3 array (int32):")
print(arr3)
print(arr3.dtype) # Output: int32

print("-" * 20)

# Create a 2x2x2 3D array of ones
arr4 = np.ones((2, 2, 2))
print("3D array:")
print(arr4)

1D array (float):
[1. 1. 1. 1. 1.]
float64
--------------------
2D array (float):
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------
3x3 array (int32):
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32
--------------------
3D array:
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [15]:
# 3x4 array of zeros
zeros_arr = np.zeros((3, 4))
print("\nZeros Array:")
print(zeros_arr)

# 2x2 array of ones
ones_arr = np.ones((2, 2))
print("\nOnes Array:")
print(ones_arr)


Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1.]
 [1. 1.]]


In [16]:
# 2x3 empty array
empty_arr = np.empty((2, 3))
print("\nEmpty Array:")
print(empty_arr) # Contains uninitialized data


Empty Array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# 2x2 array filled with 7
full_arr = np.full((2, 2), 7)
print("\nFull Array (with 7):")
print(full_arr)


Full Array (with 7):
[[7 7]
 [7 7]]


In [26]:
# Array from 0 to 9 (exclusive of 10)
range_arr = np.arange(10)
print("\nArange (0-9):")
print(range_arr)

# Array from 2 to 10 with step 2
step_arr = np.arange(2, 10, 2)
print("\nArange (2-10 step 2):")
print(step_arr)

# Array of 5 linearly spaced numbers between 0 and 1
linspace_arr = np.linspace(0, 1, 5)
print("\nLinspace (5 points between 0 and 1):")
print(linspace_arr)


Arange (0-9):
[0 1 2 3 4 5 6 7 8 9]

Arange (2-10 step 2):
[2 4 6 8]

Linspace (5 points between 0 and 1):
[0.   0.25 0.5  0.75 1.  ]


In [28]:
# 3x3 identity matrix
identity_mat = np.eye(3)
print("\nIdentity Matrix (3x3):")
print(identity_mat)

# 3x3 array of random numbers between 0 and 1
random_mat = np.random.rand(3, 3)
print("\nRandom Matrix (3x3):")
print(random_mat)



Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix (3x3):
[[0.48755313 0.59336379 0.88542346]
 [0.25271808 0.37062332 0.05111893]
 [0.05532019 0.7894133  0.09854405]]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(arr)
print("Shape:", arr.shape)      # Dimensions (rows, columns)
print("Number of dimensions:", arr.ndim) # Number of dimensions
print("Number of elements:", arr.size)  # Total number of elements
print("Data type of elements:", arr.dtype) # Data type (e.g., int32, float64)
print("Size of each element (bytes):", arr.itemsize) # Size of each element in bytes
print("Total size (bytes):", arr.nbytes)    # Total size of the array in bytes

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Number of elements: 6
Data type of elements: int64
Size of each element (bytes): 8
Total size (bytes): 48
