In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes

In [ ]:
import numpy as np

# Feature matrix X (with a column of ones for the intercept)
X = np.array([
    [1, 1, 2],
    [1, 3, 4],
    [1, 5, 6],
    [1, 7, 8],
    [1, 9, 10],
    [1, 2, 3],
    [1, 4, 5],
    [1, 6, 7],
    [1, 8, 9],
    [1, 10, 11]
])

# Target vector Y
Y = np.array([5, 9, 13, 17, 21, 6, 10, 14, 18, 22]).reshape(-1, 1)

# Applying the Normal Equation: β = (X^T X)^(-1) X^T Y
X_transpose = X.T
print(X_transpose)
x=X_transpose @ X
print(x)
x=np.linalg.pinv(x)


[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  3  5  7  9  2  4  6  8 10]
 [ 2  4  6  8 10  3  5  7  9 11]]
[[ 10  55  65]
 [ 55 385 440]
 [ 65 440 505]]
[[ 0.23838384 -0.14343434  0.09494949]
 [-0.14343434  0.08686869 -0.05656566]
 [ 0.09494949 -0.05656566  0.03838384]]
[[ 0.28484848  0.18787879  0.09090909 -0.00606061 -0.1030303   0.23636364
   0.13939394  0.04242424 -0.05454545 -0.15151515]
 [-0.16969697 -0.10909091 -0.04848485  0.01212121  0.07272727 -0.13939394
  -0.07878788 -0.01818182  0.04242424  0.1030303 ]
 [ 0.11515152  0.07878788  0.04242424  0.00606061 -0.03030303  0.0969697
   0.06060606  0.02424242 -0.01212121 -0.04848485]]
[[1.12121212]
 [0.42424242]
 [1.54545455]]
