In [ ]:
import numpy as np

# Feature matrix X (with a column of ones for the intercept)
X = np.array([
    [1, 1, 2],
    [1, 3, 4],
    [1, 5, 6],
    [1, 7, 8],
    [1, 9, 10],
    [1, 2, 3],
    [1, 4, 5],
    [1, 6, 7],
    [1, 8, 9],
    [1, 10, 11]
])

# Target vector Y
Y = np.array([5, 9, 13, 17, 21, 6, 10, 14, 18, 22]).reshape(-1, 1)

# Applying the Normal Equation: β = (X^T X)^(-1) X^T Y
X_transpose = X.T
print(X_transpose)
x=X_transpose @ X
print(x)
x=np.linalg.pinv(x)
x=x @ X_transpose
x=x @ Y
print("These are coefficients",x)

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  3  5  7  9  2  4  6  8 10]
 [ 2  4  6  8 10  3  5  7  9 11]]
[[ 10  55  65]
 [ 55 385 440]
 [ 65 440 505]]
[[1.12121212]
 [0.42424242]
 [1.54545455]]
