In [1]:
import numpy as np
# creating 1-d vector
a=np.array([1,2,3])
print(a)
# creating 2-d vector
b=np.array([[1,2,3],[4,5,6]])
print(b)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [2]:
# creating Matrices
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:-\n",matrix)

transpose=np.transpose(matrix)
print("Transpose:-\n",transpose)

# matrix multiplication
product=np.dot(matrix,transpose)
print("Product:-\n",product)
# dot product of vector and matrix

# identity matrix
identity=np.identity(3)
print("Identity Matrix:-\n",identity)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix:-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:-
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Product:-
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
Identity Matrix:-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np
# Matrix Transpose
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose=np.transpose(matrix)
print("Transpose:-\n",transpose)
# Matrix Determinant
det=np.linalg.det(matrix)
print("Determinant of Matrix:\n", det)


Transpose:-
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of Matrix:
 0.0


In [4]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2],[3,4]])
print("Matrix:-\n",arr1)
print("Matrix1:-\n",matrix1)
# Matrix Inverse
arr=np.linalg.inv(arr2)
print("Inverse of Matrix:\n", arr)

# Matrix Determinant
det=np.linalg.det(arr2)
print("Determinant of Matrix:\n", det)


Matrix:-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix1:-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of Matrix:
 -2.0000000000000004


In [5]:
import numpy as np

arr1 = np.array([[1, 3], [4, 5]])
arr2 = np.array([[5, 9], [8, 5]])

print(np.dot(arr1, arr2))


[[29 24]
 [60 61]]
